
name: Setup cache

on: push

jobs:

  # Run the build.  Will pull the cache from either an exact match
  # of the files, or the most recent cache available.  Will not push
  # any cache.
  # See prepare.yml for code to populate cache.
  Build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Restore Cache
      id: cache-restore
      uses: satackey/action-docker-layer-caching@v0.0.11
      with:
        key: docker-${{ hashFiles('utils/sl', 'utils/docker', 'utils/build.config', 'SConstruct', '.github') }}
        restore-keys: docker-
        skip-save: true
    - name: Set UID
      run: echo UID=`id -u` >> $GITHUB_ENV
      # Now do the whole build in one go.  This should just build DAOS, but
      # may build the whole stack if there are issues with the cache.
      # Splitting this out into three builds however would take extra time
      # on all builds.
    - name: Build DAOS
      run: docker build . -f utils/docker/Dockerfile.ubuntu.20.04
                          --build-arg UID --build-arg JOBS=8
                          --build-arg COMPILER=${{ matrix.compiler }}
                          --tag builder
