name: Workflow

on:
   push:
     branches:
       - master
       - 'release/*'
   pull_request:

jobs:

  Build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distro: [centos.7, centos.8, leap.15, ubuntu.20.04]
        compiler: [gcc, clang]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build ${{ matrix.distro }} Docker image with ${{ matrix.compiler }}
      run: docker build . -f utils/docker/Dockerfile.${{ matrix.distro }}
                          --build-arg COMPILER=${{ matrix.compiler }}
                          -t ${{ matrix.distro }}/${{ matrix.compiler }}/daos:${{ github.sha }}

  # Prepare docker images containing base software, plus deps.
  Prepare:
    name: Prepare images
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu.20.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set cache key
      run: echo "CACHE_KEY=$(date +%j)" >> $GITHUB_ENV
    # https://github.com/marketplace/actions/docker-layer-caching
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: daos-${{ env.CACHE_KEY }}-${{ matrix.distro }}-{hash}
        restore-keys: daos-${{ env.CACHE_KEY }}-${{ matrix.distro }}-
    - name: Build deps Docker image
      run: docker build . -f utils/docker/Dockerfile.${{ matrix.distro }}
                          --build-arg NOBUILD=1
  Build2:
    name: Run the build
    needs: Prepare
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu.20.04]
        compiler: [gcc, clang]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set cache key
      run: echo "CACHE_KEY=$(date +%j)" >> $GITHUB_ENV
    # https://github.com/marketplace/actions/docker-layer-caching
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: daos-${{ env.CACHE_KEY }}-${{ matrix.distro }}-{hash}
        restore-keys: daos-${{ env.CACHE_KEY }}-${{ matrix.distro }}-
        skip-save: true
    - name: re-build deps image
      run: docker build . -f utils/docker/Dockerfile.${{ matrix.distro }}
                          --build-arg NOBUILD=1
    - name: Build daos
      run: docker build . -f utils/docker/Dockerfile.${{ matrix.distro }}
                          --build-arg COMPILER=${{ matrix.compiler }}
                          -t build-image
    - name: check server
      run: docker run build-image ldd /opt/daos/bin/daos_io_server
    - name: Run Unit Tests
      run: docker run --name build-ut --tmpfs /mnt/daos build-image ./utils/run_test.sh
    - name: mkdir
      run: mkdir test_results/
    - name: Copy results
      run: docker cp build-ut:/home/daos/test_results/ ./
    - name: find
      run: find test_results/
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: test_results/*.xml
    - name: Run NLT Test
      run: docker run --tmpfs /mnt/daos build-image ./utils/node_local_test.py --no-root kv

  Spelling:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run check
      uses: codespell-project/actions-codespell@master
      with:
        skip: ./src/control/vendor,./.git
        ignore_words_file: ci/codespell.ignores
        builtin: clear,rare,informal,names,en-GB_to_en-US
