name: Workflow

on:
   push:
     branches:
       - master
       - 'release/*'
   pull_request:

jobs:

  Build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
#        distro: [centos.7, centos.8, leap.15, ubuntu.20.04]
        distro: [ubuntu.20.04]
        compiler: [gcc, clang]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    # https://github.com/marketplace/actions/docker-layer-caching
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: daos-docker-${{ matrix.distro }}-${{ matrix.compiler}}-{hash}
        restore-keys: |
          daos-docker-${{ matrix.distro }}-${{ matrix.compiler}}
    - name: Build ${{ matrix.distro }} Docker image with ${{ matrix.compiler }}
      run: docker build . -f utils/docker/Dockerfile.${{ matrix.distro }}
                          --build-arg COMPILER=${{ matrix.compiler }}
                          -t ${{ matrix.distro }}/${{ matrix.compiler }}/daos:${{ github.sha }}
  Native_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup node
      run: sudo ./utils/install_packages.sh
    - name: Build deps
      run: scons --build-config=utils/build.config.github --build-deps=yes --deps-only
    - name: Build
      run: scons
    - name: Install
      run: scons install

  Spelling:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run check
      uses: codespell-project/actions-codespell@master
      with:
        skip: ./src/control/vendor
        ignore_words_file: ci/codespell.ignores
        builtin: clear,rare,informal,names,en-GB_to_en-US
