name: DAOS test Build.

on:
   push:
     branches:
       - master
       - 'release/*'
   pull_request:

jobs:

  Build2:
    name: Run DAOS tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu.20.04]
        compiler: [clang]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set UID
      run: echo UID=`id -u` >> $GITHUB_ENV
    # https://github.com/marketplace/actions/docker-layer-caching
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: docker-${{ hashFiles('utils/sl', 'utils/docker', 'utils/build.config', 'SConstruct', '.github') }}
        restore-keys: docker-
        skip-save: true
    - name: Update dependencies in image.
      run: docker build . -f utils/docker/Dockerfile.${{ matrix.distro }}
                          --build-arg DAOS_BUILD=no
                          --build-arg UID -t build-image
    - name: Run inside
      run: docker run --mount type=tmpfs,destination=/mnt/daos,tmpfs-mode=1777 build-image ./daos/utils/run_in_ga.sh
